#!/bin/bash

# Monitor config -------------------------------------------
~/.screenlayout/default.sh
MAIN_MON=DP-1
SECOND_MON=HDMI-1
bspc monitor $MAIN_MON   -d chat term www dev misc
bspc monitor $SECOND_MON -d media scratch

# Settings -------------------------------------------------
bspc config border_width                  2
bspc config window_gap                    2
bspc config top_padding                   20
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         false
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier              mod4
bspc config pointer_action1               move
bspc config pointer_action2               resize_side
bspc config pointer_action3               resize_corner

# Colors ---------------------------------------------------
bspc config normal_border_color   "#4c566a"
bspc config active_border_color   "#1e1e1e"
bspc config focused_border_color  "#5e81ac"
bspc config presel_feedback_color "#5e81ac"
bspc config urgent_border_color   "#dd2727"

# Rules ----------------------------------------------------
bspc rule --add firefox     desktop='www'  follow=off
bspc rule --add Alacritty   desktop='term' follow=off
bspc rule --add Slack       desktop='chat' follow=off
bspc rule --add discord     desktop='chat' follow=off

# Autostart ------------------------------------------------
xrdb ~/.config/X11/Xresources
~/.config/polybar/launch.sh
pgrep -x sxhkd || sxhkd
feh --bg-fill --randomize ~/.local/share/wallpapers/*.jpg

