#!/bin/bash

eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets)
export $(gnome-keyring-daemon --start --components=pkcs11,secrets)
dbus-update-activation-environment --systemd DISPLAY

$HOME/.local/bin/keyboard-settings.sh &
numlockx &
picom & 
wmname compiz &

exec awesome
