#!/bin/bash

eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets)
export $(gnoe-keyring-daemon --start --components=pkcs11,secrets)
dbus-update-activation-environment --systemd DISPLAY

xset r rate 200 100 &
xmodmap ~/.config/X11/xinit/xmodmap &
numlockx &
picom & 

exec herbstluftwm
