#!/usr/bin/env bash

hc() {
  herbstclient "$@"
}

hc emit_hook reload

source "$HOME/.config/herbstluftwm/colors"

xsetroot -solid $base0B

# remove all existing keybindings
hc keyunbind --all

# keybindings
# if you have a super key you will be much happier with Mod set to Mod4
#Mod=Mod1    # Use alt as the main modifier
Mod=Mod4   # Use the super key as the main modifier

hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-x       close
hc keybind $Mod-Return  spawn "${TERMINAL:-alacritty}" # use your $TERMINAL with xterm as fallback
hc keybind $Mod-space   spawn rofi -show run

# basic movement in tiling and floating mode
# focusing clients
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients in tiling and floating mode
hc keybind $Mod-Control-Left  shift left
hc keybind $Mod-Control-Down  shift down
hc keybind $Mod-Control-Up    shift up
hc keybind $Mod-Control-Right shift right
hc keybind $Mod-Control-h     shift left
hc keybind $Mod-Control-j     shift down
hc keybind $Mod-Control-k     shift up
hc keybind $Mod-Control-l     shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-i       split bottom 0.5
hc keybind $Mod-Shift-i split top    0.5
hc keybind $Mod-o       split right  0.5
hc keybind $Mod-Shift-o split left   0.5
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames and floating clients
resizestep=0.02
hc keybind $Mod-Shift-h     resize left  +$resizestep
hc keybind $Mod-Shift-j     resize down  +$resizestep
hc keybind $Mod-Shift-k     resize up    +$resizestep
hc keybind $Mod-Shift-l     resize right +$resizestep
hc keybind $Mod-Shift-Left  resize left  +$resizestep
hc keybind $Mod-Shift-Down  resize down  +$resizestep
hc keybind $Mod-Shift-Up    resize up    +$resizestep
hc keybind $Mod-Shift-Right resize right +$resizestep

# volume control
volume_step=5
hc keybind XF86AudioMute        spawn pactl set-sink-mute 0 toggle
hc keybind XF86AudioRaiseVolume spawn pactl set-sink-volume 0 +$volume_step%
hc keybind XF86AudioLowerVolume spawn pactl set-sink-volume 0 -$volume_step%
hc keybind XF86AudioPlay        spawn playerctl play-pause
hc keybind XF86AudioNext        spawn playerctl next
hc keybind XF86AudioPrev        spawn playerctl previous

# set default layout before defining tags
hc set default_frame_layout horizontal

# tags
tag_names=( chat term www dev media misc )
tag_keys=( {1..6} 0 )

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# layouting
hc keybind $Mod-q         remove
hc keybind $Mod-s         floating toggle
hc keybind $Mod-f         fullscreen toggle
hc keybind $Mod-Shift-f   set_attr clients.focus.floating toggle
hc keybind $Mod-Shift-m   set_attr clients.focus.minimized true
hc keybind $Mod-Control-m jumpto last-minimized
hc keybind $Mod-p         pseudotile toggle
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
# hc keybind $Mod-shift-p                                                           \
#             or , and . compare tags.focus.curframe_wcount = 2                   \
#                      . cycle_layout +1 vertical horizontal max vertical grid    \
#                , cycle_layout +1

hc keybind $Mod-Control-p cycle_layout

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-m         cycle_monitor
hc keybind $Mod-Tab       cycle_all +1
hc keybind $Mod-Shift-Tab cycle_all -1
hc keybind $Mod-c         cycle

# theme
hc attr theme.tiling.reset        1
hc attr theme.floating.reset      1
hc set  frame_border_active_color $base05
hc set  frame_border_normal_color $base01
hc set  frame_bg_active_color     $base05
hc set  frame_bg_normal_color     $base01
hc set  frame_border_width        2
hc set  always_show_frame         off
hc set  frame_bg_transparent      on
hc set  frame_transparent_width   2
hc set  frame_gap                 2

hc attr theme.title_font 'FiraCode Nerd Font:pixelsize=12'  # example using Xft
hc attr theme.background_color      $base00
hc attr theme.border_width          0
hc attr theme.title_height          0
hc attr theme.title_color           $base05
hc attr theme.padding_top           2
hc attr theme.padding_bottom        2
hc attr theme.color                 $base04
hc attr theme.active.color          $base05
hc attr theme.normal.color          $base01
hc attr theme.urgent.color          $base08
hc attr theme.normal.title_color    $base05
hc attr theme.inner_width           1
hc attr theme.inner_color           $base00
hc attr theme.floating.border_width 2
hc attr theme.floating.outer_width  2
hc attr theme.floating.outer_color  $base00
hc attr theme.active.inner_color    $base05
hc attr theme.urgent.inner_color    $base08
hc attr theme.normal.inner_color    $base01
# copy inner color to outer_color
for state in active urgent normal ; do
    hc substitute C theme.${state}.inner_color \
        attr theme.${state}.outer_color C
done
hc attr theme.active.outer_width 2
hc set window_gap                0
hc set frame_padding             0
hc set smart_window_surroundings off
hc set smart_frame_surroundings  on
hc set mouse_recenter_gap        0

# rules
hc unrule -F
hc rule class="firefox" tag="www"     # all firefox windows in the www tag
hc rule class="Alacritty" tag="term"  # all alacritty windows in the term tag
hc rule class="discord" tag="chat" focus=off  # all discord windows in the chat tag
hc rule class="Slack" tag="chat" focus=off    # all slack windows in the chat tag
hc rule focus=on # normally focus new clients
hc rule floatplacement=smart
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

hc set tree_style '╾│ ├└╼─┐'

# unlock, just to be sure
hc unlock

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
# bash ~/.screenlayout/1mon.sh
hc detect_monitors
hc set_monitors 2560x1420+0+20
nitrogen --restore

# find the panel
panel=~/.config/polybar/launch.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
"$panel" "herbstluftwm" &
